### PR TITLE
Updated solution structure (#79)

### PR DESCRIPTION
**Pull request by Ketrex**
This PR brings the solution structure in line with the aspnet team's project code structure.

### CODE REVIEW

**Comment by Ketrex** [comment]
Whoops, thanks for catching that! Update has been submitted.

**Comment by MarkPieszak** [comment]
Strange it still has them being included, 
src/Angular2Spa/Client/dist/main-server.js
src/Angular2Spa/Client/dist/0.js
etc.

**Comment by Ketrex** [comment]
hmmmm, I'll take another look. Thanks.

**Comment by Ketrex** [comment]
Heh, case-sensitivity, sheesh! I'll have an updated PR momentarily.

**Comment by MarkPieszak** [comment]
Silly gitignore :)
In my opinion it shouldn't be case-sensitive...

**Comment by Ketrex** [comment]
should be good to go now.

**Comment by MarkPieszak** [comment]
Sorry for the delay Kevin!! @Ketrex 
I've been unbelievably swamped :(

Finally merged it into Master, so far everything is working great.
Added a nice little package.json that cd's into src/angular2spa to just run the install/webpack stuff (from root), and fixed up the vscode launch & settings & task files to run from Root as well :)

Any other ideas let us know!
Working on Upgrading to **Angular 4.rc** right now

**Pull request merged**
