### PR TITLE
(Unit Testing) Run unit testcases using PhantomJS in Continuous Integration environments

### PR DESCRIPTION
**Pull request by davidsekar**
- npm run test  -> runs tests using chrome browser
- npm run test:ci -> runs tests using phantomjs ( suitable for CI )
- npm run test:watch, npm run test:ci:watch -> watch mode

- Speed up build/rebuilding unit testcases (using DLLBundlePlugin - **vendor.js**) .

- removed deprecated tslint rules and updated the modified ones.

### CODE REVIEW

**Comment by MarkPieszak** [comment]
There are some issues with DLLBundle and AoT typically, were you able to produce prod bundles even with that in Vendor ?

**Comment by MarkPieszak** [comment]
This looks fantastic though otherwise !

**Comment by davidsekar** [comment]
This PR uses DLL for speeding up testcase rebuild time & DLL plugin did work fine as i was building it in **development mode**(not prod mode).

I had issue with AoT and lazy loading in SSR for the prod builds, but that doesn't affect this PR.

**Comment by davidsekar** [comment]
The creator of DLL plugin has commented that the DLLPlugin is not for production builds as it prevent few benefits the webpack loaders can do.  
https://github.com/shlomiassaf/webpack-dll-bundles-plugin/issues/21#issuecomment-322239295

AOT + DLLPlugin + Lazy - seems not working for months
So not sure why dotnet SPA Angular template has this DLL plugin enabled for production build.

I will remove the DLL plugin and test.

**Comment by MarkPieszak** [comment]
Yeah there are some issues that the team is working on in regards to all of that, it's definitely complicated ! Let me know when I can merge this though!

**Comment by davidsekar** [comment]
@MarkPieszak You can merge this PR as the unit tests are **_not_** executed against AoT bundle. So it works fine with current DLLPlugin setup.

**Comment by jrmcdona** [comment]
@davidsekar do you know why the Coverage report doesn't show errors?  Seems to just focus on coverage.   What do you use for outputting errors on CI build?

**Comment by davidsekar** [comment]
Try **npm run test:ci**, which uses phantomjs to run your test cases and then generates code coverage.

If you want to debug test cases, then run with chrome **npm run test** which also generates coverage. 

I have not tested npm run coverage, which was earlier used with Zest. Will try to check and see how that one works

**Pull request merged**
