### PR TITLE
(Unit testing) using Karma test runner 

### PR DESCRIPTION
**Pull request by davidsekar**
1) Based on reply in Angular CLI project project thread. 
https://github.com/angular/angular-cli/issues/4543#issuecomment-303364585

2) I was unable to write unit test for the contents shown on **ngx-bootstrap** modal, as the BsModalService requires
window.getcomputedstyle().getpropertyvalue(), which is hard to polyfill in jsDom (used by Jest)

3) Code coverage using istanbul

4) In favour of readme file
> Unit testing with Jest (Going back to Karma soon)

### CODE REVIEW

**Comment by davidsekar** [comment]
Ideas taken from 
1) JavascriptServices - Angular SPA
2) AngularClass/angular-starter

**Comment by MarkPieszak** [comment]
This is fantastic! Yeah I think ideally we might as well stick with the default as Jest doesn't offer the same type of testing. I'll move the Jest stuff into a HOW TO PR, for others to see at least!

👍👍🍻🍻

**Comment by jrmcdona** [comment]
I deleted ngx-bootstrap from my app.  Do I need to worry about this?

Is this a bigger issue or is this PR just to fix testing ngx-bootstrap modal testing?

**Comment by jrmcdona** [comment]
@davidsekar @MarkPieszak   Is this something I need to be pulling in?  Or just an issue with testing ngx-bootstrap which I don't use in my app

**Comment by MarkPieszak** [comment]
It's up to you, this is just if you want the traditional way Karma does testing (with a browser) as opposed to Jest, which can't do that. @jrmcdona

**Pull request merged**
