### PR TITLE
Added REST API and example 

### PR DESCRIPTION
**Pull request by LiverpoolOwen**
Hello mate,

I didn't mean to close the other pull request I was deleting some of my remote branches after merging back to master.

Anyway, let me know what you think of the changes.

Thanks.

### CODE REVIEW

**Comment by MarkPieszak** [comment]
This looks excellent! Nicely done!
Cheers 🍻

**Comment by MarkPieszak** [comment]
We can split it up into a Service in ./shared/users/user.service.ts later, otherwise looks great

**Comment by LiverpoolOwen** [comment]
Good idea mate, I will sort that out later. I will make the table a bit prettier as well I think amd throw some extra angular validation on there as well maybe.

**Comment by LiverpoolOwen** [comment]
What's the highest priority work for this do you think atm?

**Comment by MarkPieszak** [comment]
I have AoT "basically" working, but I need to figure out one issue it's throwing that seems to be something overall going wrong with `@ngtools/webpack`, but I'm investigating now.

I wanted to get ng2-bootstrap with bootstrap4 & SASS (for themeing) in there, but feel like that might be a next step for after AoT is finished.

Maybe some type of basic Authentication would be nice? ala #59?

Also not sure if #149 is fixed, but guessing so.

**Comment by LiverpoolOwen** [comment]
Cool I will look into these and try get something done

**Comment by MarkPieszak** [comment]
The fonts for glyphicons weren't coming through bootstrap-sass, you can see the 404s in the browser, gotta figure that one out too.

**Pull request merged**
