### PR TITLE
Remove uglify

### PR DESCRIPTION
**Pull request by OceansideBill**
I know another PR was created that handles the imports to support uglify.  However, I'm suggesting that instead we omit it.   It appears to have become obsolete in the latest version of WebPack.  Of note I found issues with .NET Core and the way the references for 2.1 was modified in the CSProj file when I tried to run and have restored those.  This build also includes some clean-up related to the readme.MD file as well as the transition to the new angular/cli json format: angular.json.  It builds in both dev and production, and also runs in both.

### CODE REVIEW

**Comment by RZeni** [comment]
Did u update to the latest .NET SDK and runtime needed to run 2.1 before reverting? 
SDK - https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1
Runtime - https://www.microsoft.com/net/download/dotnet-core/runtime-2.1.0-rc1 
Everything else looks good.

**Comment by MarkPieszak** [comment]
Hey guys sorry I've been trying to keep up with everything, do we know if this one is all set, or was there something else you needed to update here? @OceansideBill

**Comment by MarkPieszak** [comment]
I just updated the project, we should be all set now - it looks like things work even with the latest uglify webpack plugin and webpack 4.

`npm run build:prod` works perfectly here after this commit :+1:

https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/eff67f28a986be7fb36b16d002649e6ea37622e2

I think we can close this one out for now @OceansideBill, thank you for your help pointing these issues out!! 🎁 🥇

**Comment by BillSheldon-HunterIndustries** [comment]
Mark I'm good with withdrawing this push tonight when I get home.  However, I think you all missed why I removed the Uglify settings.  It wasn't that I couldn't get them to work, it was that WebPack 4 incorporates uglify and produces a smaller package when we remove the custom settings.  Here's a blog post that discusses the changes with WebPack 4: https://blog.pusher.com/whats-new-webpack-4/

**Comment by MarkPieszak** [comment]
Is it a major change we'd have to make with what we have in the repo now, or just a few updates we'd have to make at this point?

**Comment by OceansideBill** [comment]
I'm going submit a replacement with only the uglify removal, it's fairly minor I just need to get it isolated.

**Comment by RZeni** [comment]
While you are correct that webpack 4 uses uglify internally, though the default config for such does not preserve class names. This causes the StaticInjectorError when launching in production. So we need to define a custom uglify config to workaround this issue until it is fixed. See #639

**Pull request closed without merging**
