### PR TITLE
Entity Framework Example with documentation added

### PR DESCRIPTION
**Pull request by AbrarJahin**
Entity framework REST API with Documentation added.

The code is done with Code First and DB used is SQLite.

So, no need to face any kind of configuration problem.

It is just as before.

You just need to clone the code and run, everything will be set up for you !!!!!!

### CODE REVIEW

**Comment by AbrarJahin** [comment]
That would be great.

Thanks.

And also, the code is base on CodeFast approach, and seeder is also added (not sure if it is the best approach to add seeder - https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Startup.cs#L104 ).

If there any better approach to add seeder, please add that @MarkPieszak 

Thanks 👍

**Comment by MarkPieszak** [comment]
We could just move it into a separate file, but otherwise it looks fine to me!
Great job again 👍

**Comment by AbrarJahin** [comment]
And please, if you try to make a showcase, before that I am requesting this issue to be solved-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/48

So that the security of our template would be better.

Thanks again 💯

**Comment by MarkPieszak** [comment]
Sure! I'll take care of that before anything else.
Not a problem.

**Comment by AbrarJahin** [comment]
Thanks 👍

**Pull request merged**
