### PR TITLE
Issue #79: Further modifications to solution structure

### PR DESCRIPTION
**Pull request by markwhitfeld**
As mentioned in my [comment](https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/79#issuecomment-282693175) on issue #79, this is a refactor to move the .net core project into a separate folder to the Angular 2 SPA

### CODE REVIEW

**Comment by markwhitfeld** [comment]
One thing I wasn't sure about after my rename was if I should leave the `src\Angular2Spa\Client` folder called `Client`. According to the [recommended file structure](https://angular.io/docs/ts/latest/guide/style-guide.html#!#file-tree) for an Angular2 app it should have the code under an `src` folder. If we were to say that the `src\Angular2Spa` folder is our project root then we should rename the `Client` folder to `src`.
This would result in a folder structure of:
- src
  - Angular2Spa
    - src
      - app
      - containers
      - ...
    - node_modules
    - ...
  - AspCoreServer
    - Client
    - wwwroot
    - ...
Do you think I should include this change?

**Comment by albrookesplowman** [comment]
Hi guys, I am fairly new to this template and i think it is a great idea and will look to contribute when/where I can.  I am afraid that I will have to fit it in around my day! :)   I think that this structure looks nice especially if the plan is that the AspCoreServer side is going to be a minimal approach just to service the .NET Core code etc.. This would allow all the business logic and further services / domain models etc.. to be written in separate libraries/modules and this would aid testing.  

I am fairly new to Angular 2 but have been writing backend servers and other C# applications for several years now and I am very excited about the whole Angular road-map and would like to get involved as and when I can..  Are there any reference documents to what is planned in Angular 4 etc...  Looking forward to working with you all :)

Al

**Comment by MarkPieszak** [comment]
I'll get ng 4.0 updates in here probably in a week or so (I'm gone this week). I'm just waiting for it to get closer to release time. :) @albrookesplowman 

@markwhitfeld Looking over the changes everything looks good so far!
Did you test out creating `dotnet publish` or pushing this to Azure / etc ?

It looks now the `Angular2Spa` project is literally only for Development while AspCoreServer is what we're really pushing up now right?

**Comment by MarkPieszak** [comment]
I'm going to merge this in, this is awesome man wow incredible job!!! @markwhitfeld 💯 💯 
Let's test out how Azure publish & dotnet publish work now, can fix anything that goes wrong there.

You're right let's rename client in Angular2Spa, i'll merge this in see for now, you can put in a new PR with that or any other updates you see! Amazing man 🥇

**Comment by fmeira** [comment]
Seems that not all the work has been done here.. The new solution file points to a project "src\AspCoreServer\AspCoreServer.xproj" which does not exist, and it doesn't seem to even have a entry for the Angular2Spa (client app) project..

**Comment by MarkPieszak** [comment]
Did you pull down a fresh repo (in a new folder) as well? Let me try that as well @fmeira

**Comment by MarkPieszak** [comment]
@markwhitfeld It looks like it's a problem with Visual Studio (2015). Angular2Spa isn't showing up, and yeah AspCoreServer.
Looking at it now @fmeira

**Comment by MarkPieszak** [comment]
Checked in https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/925b709feeeb63255356f237ecb4ce350cb08691 @fmeira try it again.

Give it a shot.

I had to manually add each individual file :(
At least it works now, I'm sure in VS2017 I'll have an easier way to do all of this.

**Comment by fmeira** [comment]
Thanks for the effort, though it still acted weird. The angular part was loaded as a folder and only the root files were part of the solution. It would not compile/build.

I would expect to find a .xproj for the Angular2Spa. I understood that the main idea behind this re-structuring was to separate out the web API part to another project. Thus, there should be 2 projects not just one (not counting the test proj here). 

I ended up getting it to work by adding the project file for the angular part and updating the solution file (and a project.json file). Not sure that this is the way you guys planned, so did not submit a PR, but can do if needed.

Oh yes, I'm on VS 2015, maybe this all goes smoother on VS2017, have not tried it.

**Comment by AbrarJahin** [comment]
I am also finding the error @MarkPieszak

**Comment by AbrarJahin** [comment]
I got the error.

It is occuring because of this-

Problem is in this line-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/src/AspCoreServer/prepublish.cmd#L2-L3

And this line-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/src/AspCoreServer/prepublish.cmd#L7

Mainly in Line no-3

We should update that

**Pull request merged**
