### PR TITLE
Added REST API back into project

### PR DESCRIPTION
**Pull request by LiverpoolOwen**
Basically, just the rest API that was set up before. I can implement a page which makes use of these as well if this is what is wanted?

### CODE REVIEW

**Comment by MarkPieszak** [comment]
Why not, it'd be nice to have 🎈
Let's add all the contributors in there if we can ! 🎁
Thank you again Owen!! :1st_place_medal:

**Comment by LiverpoolOwen** [comment]
No problem mate. It's quality work you have done on this template.

**Comment by MarkPieszak** [comment]
Thank you glad it's helping people out ! Still a few things to get it up to speed.
I need to hustle as I need to have it done before ngConf this week 😖

**Comment by MarkPieszak** [comment]
Want to wait to merge it or are you doing the rest in a separate PR?
Up to you!

**Comment by LiverpoolOwen** [comment]
That's cool, send me the link if it's recorded. 

Yeah I will add it in the same PR. Still getting use to how git hub works tbh. That was my first pull request yesterday. I have been a dev for years but not worked on any open source till now.

**Pull request closed without merging**
