### PR TITLE
Created User service

### PR DESCRIPTION
**Pull request by LiverpoolOwen**

### CODE REVIEW

**Comment by LiverpoolOwen** [comment]
I see the documents for the web API in the root folder, they would now need updating after the web API changes I made earlier or we could remove them? It is pretty basic web API stuff really so I am not sure we need this at all TBH but if we are going to have API documentation we may be better implementing Swagger or something similar? so the documentation is built into the code?

I noticed there is no server side unit testing anymore, is this going to be added back in?

**Comment by MarkPieszak** [comment]
Yeah we need to add that back in, and you're right Swagger would be excellent!

**Comment by LiverpoolOwen** [comment]
I just added Swagger locally and it was easy to set up but the MapSpaFallbackRoute causes a redirect. Any ideas on how we can exclude this from the fallback?

**Comment by LiverpoolOwen** [comment]
image

**Pull request merged**
