### PR TITLE
Issue #160 Replace Karma test runner with Jest

### PR DESCRIPTION
**Pull request by andersk2**
# Overview

[Jest](https://facebook.github.io/jest/), the _delightful_ test runner from facebook, is quite capable when it comes to testing angular components.
This PR adds `jest` along with a `jest-preset-angular`

# Key features

* The tests work
* No changes to spec-file(s)
* Improved speed for first run
* Much improved speed for consecutive runs (using `npm run test:watch`)
* Comes with coverage support out of the box

### CODE REVIEW

**Comment by MarkPieszak** [comment]
@andersk2 This is incredible man!! Nice! 💯 💯 

With the `tsconfig` changed a little bit, were you still able to run `build:dev` and `build:aot` without any problems?

Been meaning to try Jest!

**Comment by andersk2** [comment]
@MarkPieszak Yes. The `build:aot` task produced some warnings though, but still run just fine

**Comment by MarkPieszak** [comment]
Those are mainly from ng2-bootstrap, but they'll go away when we can upgrade that.
Excellent I'll merge this in!! Great idea with Jest 👍

**Comment by rfuhrer** [comment]
@andersk2 Any chance you could add a "Debug Tests" to the launch.json?  I have a test that's failing with an odd exception (must be setting up the TestBed wrong because it works outside of Jest) and it would be nice to be able to debug your unit tests.

Here's what I've got so far which runs the test runner successfully, however it is unable to see the link between the sourcemaps and the generated code:
```
        {
            "type": "node",
            "request": "launch",
            "name": "Run Tests",
            "program": "${workspaceRoot}/node_modules/jest-cli/bin/jest.js",
            "args": [
                "--runInBand"
            ],
            "runtimeArgs": [
                "--nolazy"
            ],
            "stopOnEntry": false,
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,            
            "console": "internalConsole"
        }
```

It seems like there should be something in the "OutFiles" to point to the generated code, but with webpack we're not just dumping a million .js files into a folder somewhere that we can point at.

Thanks!

**Comment by MarkPieszak** [comment]
I haven't tried debugging Jest in VSCode personally but it looks like it may be possible? Found this link here, maybe it can help you out? http://www.markuseliasson.se/article/debugging-jest-code/ 
Would be a great addition for others in the repo if you do figure it out! @rfuhrer

**Comment by rfuhrer** [comment]
Yeah I've been trying a bunch of those examples but none of them are using a setup similar to this one (almost all of them seem to be angular CLI projects).  That's why I was hoping Anders could take a crack at it since he setup the Jest configuration.  Even if I manually run webpack and then point the debug OutFiles at the generated files, your breakpoints still grey out in VS Code saying "Breakpoint ignored because generated code not found (source map problem?)"

If I do figure it out, I'll add a pull request for sure.

**Comment by rfuhrer** [comment]
Just an update here.  I never did get this working and then I ended up changing my project to use Karma instead because I'm using Angular Material 2 and there's still some issues around testing things like a Dialog when there's no real dom.  Now that Chrome 59 has a headless mode it feels pretty comparable to Jest in terms of speed and not clogging up your workspace with a window that you never look at.

**Comment by MarkPieszak** [comment]
Ahh very nice, so we might be able to just go back to Karma then? @rfuhrer

**Comment by rfuhrer** [comment]
I really liked Jest, but until every library 100% supports not having a dom or can have the dom function required easily mocked out, you're kind of stuck to just testing logic.  At least that was my experience, someone else might have figured out how to get it all working with Jest.

I guess it depends on the goal of this starter project.  If it's to basically be what Angular CLI would produce if it had a "dotnet core" option, then it would probably be best to stick with Karma/Protractor since that's what the Angular team seems to still be recommending.  If this is supposed to be a kitchen sink style of approach where people should remove the things they don't need, then you could probably support both Jest and Karma and just leave some notes that one should probably be removed once you've evaluated which one fits your needs better.

**Comment by MarkPieszak** [comment]
Yeah I'll have to switch back to karma and leave a reference to this, incase someone wants jest. After talking with the team the other week I realized jest doesn't fit all the needs for testing (as you were just saying).

**Pull request merged**
