### PR TITLE
feat(Angular 5.0): update engine-etc for angular 5.0 & Domino

### LINKED ISSUE #424: Issues with Styles approach in ngAspnetCoreEngine
I am using `Angular 4.4.3`, and` angular/material 2.0.0-beta.11` and `ngAspnetCoreEngine `form this repository in one of my projects. There is a slight difference the way I am setting `title `and `canonical tags `in my app. Since majority of the pages in my case are dynamic and both title and canonical tags are dynamic as well. Therefore instead of setting title and links from App component on (router change subscription) I set title and links from the component corresponding to the page. For title I am using Title service from Angular and for Links I am using Links server from this repo.

Today when I inspected the generated markup of few pages of my app. I found duplicate title and canonical tags.

I did some research and found that the issue is due to the way `ngAspnetCoreEngine `fetches the styles:

```
let STYLES_STRING: string = htmlDoc.indexOf('<style ng-transition') > -1
                                    ? htmlDoc.substring(
                                        htmlDoc.indexOf('<style ng-transition'),
                                        htmlDoc.lastIndexOf('</style>') + 8)
                                    : null;
```

Since I am using Material it appends several `style ` tags to the `Head `element, each tag containing styles related to specific component or group of components. Now when I add Title from my component its not always the first element after `<head>` tag. Sometimes its after few styles tags, followed by few other style tags.

Although using the above approach, selects all style tags but it also select the title and meta tags if they fall in between style tags. As a result the final markup which is sent from the server to the browser contains multiple Title tags. One form globals.title and other from the globals.styles.

There is some code in ngAspnetCoreEngine, but its commented 

```
// Broken after 4.0 (worked in rc)
                  // if (element.name === 'style') {
                  //   let styleTag = '<style ';
                  //   for (let key in element.attribs) {
                  //     if (key) {
                  //       styleTag += `${key}="${element.attribs[key]}">`;
                  //     }
                  //   }

                  //   styleTag += `${element.children[0].data}</style>`;
                  //   STYLES.push(styleTag);
                  // }
```
I uncommented the above code in ngAspnetCoreEngine and updated the resolve statement to the following:

```
resolve({
                  html: APP_HTML,
                  globals: {
                      styles: STYLES.join(' '),
                    title: TITLE,
                    scripts: SCRIPTS.join(' '),
                    meta: META.join(' '),
                    links: LINKS.join(' ')
                  }
                });
```

And it started working perfectly.

Based on above, I think the styles approach in current ngAspnetCoreEngine requires an update. There is a comment in above code which says `// Broken after 4.0 (worked in rc)` I am not sure what exactly is broken, its working perfectly fine with ` Angular 4.4.3`.

### LINKED ISSUE #430: @universal/ng-aspnetcore-engine usage in boot.server.ts
Hello-

Any reason why boot.server.ts. doesn't use @universal/ng-aspnetcore-engine?
// Temporary * the engine will be on npm soon (`@universal/ng-aspnetcore-engine`)

I see it is installed in package.json.  

The documentation says to reference this app:
https://www.npmjs.com/package/@nguniversal/aspnetcore-engine

I assume just lack of time and/or nobody PR'd it.   But wanted to double check if it is stable.

Thanks

### LINKED ISSUE #434: Latest Clean Build - fails
I'm running node v8.6 and npm 5.4.2.

Pulled a copy of the latest changes to my local machine.  
Immediately failed on npm install.
Reran npm rebuild node-sass - didn't help
Deleted my node_modules folder and did a fresh npm install.
This worked, for npm install.

npm run build:dev then failed.

Getting an errors TS2345 and TS2034.

I'm holding off updating my fork 
build-dev

### LINKED ISSUE #435: Slow HMR speed
Hot reload takes about 5-6 seconds after any change in the code. Is there anything that can be done to speed this up? This project contains a lot of features, maybe a cleaner project with fewer features would help? By comparison, a clean cli project takes about 1-2 seconds to reload.

### PR DESCRIPTION
**Pull request by MarkPieszak**
Fully-Functioning version updated to work with Angular 5.0-rc1.
Waiting until we merge updates to Aspnet-engine (in universal): https://github.com/angular/universal/pull/825

Before officially merging into Master branch.

WIP - More updates to come

Closes #434 
Closes #435 
Closes #430 
Closes #424 

🎁 🍾

### CODE REVIEW

**Comment by isaac2004** [comment]
@MarkPieszak since this is working (great job by the way). Do we want to clean up that mast branch to be lean with this PR? I can wait till after to create one as well

**Comment by naveedahmed1** [comment]
A clean up is much needed!

**Comment by MarkPieszak** [comment]
Yes definitely 👍👍 If you want to take the branch for a spin and clean anything up just make commits right to this branch and we'll merge them all into master.
Then it'll be easier to do the "how-to's" that add more functionality (maybe in PRs we intentionally never merge (?))

**Comment by naveedahmed1** [comment]
@MarkPieszak can't we just replace the existing TransferHttp module with a simple interceptor like this? This way it seems more aligned with the theme of new HttpClientModule.

```
import { Injectable, Inject, PLATFORM_ID } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest, HttpResponse, HttpErrorResponse, HttpEventType } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { TransferState } from './../modules/transfer-state/transfer-state';
import { isPlatformServer } from '@angular/common';

import { ORIGIN_URL } from './shared/constants/baseurl.constants';

@Injectable()
export class CustomHttpInterceptor implements HttpInterceptor {

    private isServer = isPlatformServer(this.platformId);

    constructor(
        @Inject(PLATFORM_ID) private platformId,
        protected transferState: TransferState,
        @Inject(ORIGIN_URL) private baseUrl: string) { }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        let modifiedRequest: any;
        let url: string;

        let isLocalRequest: boolean = !req.url.startsWith('http');
        if (isLocalRequest) {

            url = (isLocalRequest ? this.baseUrl + req.url : req.url);

            // Skip cache check if the request method isn't GET.
            if (req.method == 'GET') {
                const cachedResponse = this.getFromCache(url);

                if (cachedResponse) {
                    // A cached response exists. Serve it instead of forwarding
                    // the request to the next handler.

                    let modifiedResponse = new HttpResponse<any>({ headers: cachedResponse.headers, body: cachedResponse.body, status: cachedResponse.status, statusText: cachedResponse.statusText, url: cachedResponse.url });
                    return Observable.of(modifiedResponse);
                }
            }

            // Clone the request to add the new header.
            modifiedRequest = req.clone({ headers: req.headers, url: url, body: req.body });
        }

        return next.handle(isLocalRequest ? modifiedRequest : req)
            .do((event: HttpEvent<any>) => {
                if (event instanceof HttpResponse) {
                    if (this.isServer) {
                        this.setCache(url, event);
                    }
                }
            });
    }

    private setCache(key, data) {
        return this.transferState.set(key, data);
    }

    private getFromCache(key): HttpResponse<any> | null {
        return this.transferState.get(key);
    }
}
```

**Comment by MarkPieszak** [comment]
We'll definitely be getting rid of the need to have TransferHttp locally, as we basically moved a similar one into Angular Core itself in 5.0. :)

As for an interceptor to auto-append the current base_url, we definitely might as well add it!

**Comment by isaac2004** [comment]
@MarkPieszak this is probably safe to merge since your PR in Universal is merged as well. Only thing left pending is the transferhttp stuff right?

**Comment by naveedahmed1** [comment]
Below is the updated interceptor, which should work with Angular 5.

```
import { Injectable, Inject, PLATFORM_ID } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest, HttpResponse, HttpErrorResponse, HttpEventType } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { TransferState } from '@angular/platform-browser';
import { isPlatformServer } from '@angular/common';

import { ORIGIN_URL } from './shared/constants/baseurl.constants';

@Injectable()
export class CustomHttpInterceptor implements HttpInterceptor {

    private isServer = isPlatformServer(this.platformId);

    constructor(
        @Inject(PLATFORM_ID) private platformId,
        protected transferState: TransferState,
        @Inject(ORIGIN_URL) private baseUrl: string) { }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        let modifiedRequest: any;
        let url: string;

        let isLocalRequest: boolean = !req.url.startsWith('http');
        if (isLocalRequest) {

            url = this.baseUrl + req.url;

            // Skip cache check if the request method isn't GET.
            if (req.method == 'GET') {
                const cachedResponse = this.getFromCache(url);

                if (cachedResponse) {
                    // A cached response exists. Serve it instead of forwarding
                    // the request to the next handler.

                    let modifiedResponse = new HttpResponse<any>({ headers: cachedResponse.headers, body: cachedResponse.body, status: cachedResponse.status, statusText: cachedResponse.statusText, url: cachedResponse.url });
                    return Observable.of(modifiedResponse);
                }
            }

            // Clone the request to add the new header.
            modifiedRequest = req.clone({ headers: req.headers, url: url, body: req.body });
        }

        return next.handle(isLocalRequest ? modifiedRequest : req)
            .do((event: HttpEvent<any>) => {
                if (event instanceof HttpResponse) {
                    if (this.isServer) {
                        this.setCache(url, event);
                    }
                }
            });
    }

    private setCache(key, data) {
        return this.transferState.set(key, data);
    }

    private getFromCache(key): HttpResponse<any> | null {
        return this.transferState.get(key, null as any);
    }
}
```

**Comment by MarkPieszak** [comment]
Sometimes yes, but in this case since it's an InjectionToken from completely outside of itself, we need to do get it via the Injector, otherwise you get the quite vague error:

```
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler.
```

**Comment by MarkPieszak** [comment]
@naveedahmed1 Good news, soon there will also be built in support for automatically adding relative path in Core :)
https://github.com/angular/angular/issues/19224

Since we essentially do need them to make sure transfer stuff works.

**Comment by naveedahmed1** [comment]
That would be awesome! Meanwhile I am not able to successfully implement ServerTransferStateModule from Angular 5, can you please also take a look at https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/448

**Comment by MarkPieszak** [comment]
I didn't have much time today, but ServerTransferStateModule seems to break server-renders for the time being, I'm going to merge this into Master, and hopefully one of us can figure out what's causing that to break, and we can eventually get that in there as well! :)

**Comment by naveedahmed1** [comment]
@MarkPieszak can TransferHttpCacheModule ( https://github.com/angular/universal/tree/master/modules/common ) be used in this case?

It says:

> This is the common Angular Universal module that is common across server-side rendering app irrespective of the rendering engine.

I tried adding it, though it doesn't break the app. but the requests are still rendered twice once on server and once on client.

**Pull request merged**
