### PR TITLE
Added a working SignalR Chat page

### PR DESCRIPTION
**Pull request by hakonamatata**

### CODE REVIEW

**Comment by MarkPieszak** [comment]
Is this with the 4.0 branch as well? Very nice :+1: :100: :goal_net: 
When we get the conflicts resolved I'll pull it in, so we can merge.

I'm going to move the old 2.x stuff into a new branch as well in case people still use that.

**Comment by hakonamatata** [comment]
You can check it out here: 

[http://signalr-example.azurewebsites.net](http://signalr-example.azurewebsites.net)

Tried to not make any changes, just additions. So think the conflicts should be easily resolved.

**Comment by MarkPieszak** [comment]
Glad you did this on the 4.0 branch, did you have any other problems with VS2017 / etc?

Let me pull down the PR and take a look! :)

**Comment by hakonamatata** [comment]
Thanks @MarkPieszak  :)

Did not really have any problems with VS2017 or Angular 4. Worked like a charm. 
Publishing to Azure as well. 

Next thing I want to add is Redux, so I can use Redux Dev Tools. 
I'll start that next

> We can always do a separate PR for anything else you want to do!

Not sure what you mean by this? A separate pull request?

**Comment by MarkPieszak** [comment]
Yeah if you want to add Redux for example, separate PR for sure :)

**Comment by MarkPieszak** [comment]
Working on the merge now

**Comment by M-R-Bishop** [comment]
I'm having a heck of a time getting the chat example to connect.  Before the page renders I get an error saying: Failed to connect. Error: Error during negotiation request

Now I was thinking maybe it has to do with cross domain requests connecting to an Azure backend, but the weird thing is - I get this same error trying to run my own personal project with SignalR (was hoping the demo might show me what I was doing wrong).  Looks like the error occurs during the "negotiating" step (jquery.SignalR.js line 667).  It looks like the jQuery ajax call never actually runs.  

Any ideas what I'm doing wrong?  Everything works fine in my own if I revert the project back to Angular 2.48.  Can't figure out why neither of these Angular 4 SignalR projects will connect locally.

**Comment by MarkPieszak** [comment]
I haven't tried In a little while, I noticed someone else posted the same issue w local host. 
Not sure what could of changed all of this was working not long ago.. Ideally it shouldn't matter what version, it was working here with 4.0 here, have you tried pulling down this commit specifically seeing if it makes any difference?

**Comment by M-R-Bishop** [comment]
Did a bit more digging and actually I'm getting an error before on line 671 of jquery.SignalR.js 'TypeError: Cannot read property 'apply' of undefined'

image

I'm not able to determine where this is happening with the Chrome debugger.  However if I switch over to IE11 it looks like it's happening inside '@angular\common\@angular\common.es5.js'. (line 3109)
 
image

Doesn't look like this file is included in Angular 2.4 so I'm guessing this must be the culprit.  Any idea what this might be?  Let me know if I should open a separate issue.

**Comment by MarkPieszak** [comment]
Ahh so this is an issue with IE, `Object.assign` doesn't exist on any version of IE ( way to go IE :disappointed: ), so you're going to want to include the polyfills in the `./Client/polyfills/polyfills.ts` file.

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/polyfills/polyfills.ts#L6-L19

I might have to include the `import 'core-js/es6/object';` one by default for this scenario.

**Comment by M-R-Bishop** [comment]
I managed to solve this with a few different steps.

1.)  Uncommenting the polyfills from polyfills.ts fixed the SignalR error for IE11 but not other browsers.  
2.)  It turns out there was a bug released with zone.js 0.8.8 (see here: https://github.com/angular/angular-cli/issues/6036).  Deleting zone from node modules and upgraging to 0.8.9 fixed SignalR for the other browsers.

Hope this helps!

**Pull request merged**
