### PR TITLE
feat(AoT): :sparkles: :sparkles: added initial AoT support any many other things

### PR DESCRIPTION
**Pull request by MarkPieszak**
> Made this one a PR since it's quite a massive change, I'm also going to drop some of the older naming conventions and stick with ones from the Angular style guideline. `main.server.ts` for example as opposed to `boot-server`

Added Bootstrap with SCSS / SASS support
Added ng2-bootstrap
Passing Server originURL so that URLs can use it (when 4.1 comes out
with HttpInterceptors this will be even easier to do)

:sparkles: **AoT added ! for prod (npm run build:aot)**
 - Note: We still need to test this for Azure deployments etc

Removed es6-shim added core-js

Few other misc things...

### CODE REVIEW

**Comment by hheexx** [comment]
@MarkPieszak 
No more vendor bundle?

**Comment by MarkPieszak** [comment]
At the moment no, had to get it working first had some hurdles to get around 🙈
There are ways of splitting it without doing a separate file we can do eventually.

**Comment by hheexx** [comment]
HMR code in main.browser.ts is patched in memory by ngtools?

**Comment by hheexx** [comment]
@MarkPieszak 
Also, why you have seperate entry file for aot on server and not in a browser?
Is there a benefit of running aot on server?

**Comment by hheexx** [comment]
You did not hit this bug https://github.com/angular/angular-cli/issues/5329 ?

**Comment by MarkPieszak** [comment]
Ng tools automatically handles the browsers AoT files, server will be able to do the same thing soon, but that's the only reason there are duplicate (sort of) files for server and server.aot and the tsconfigs.

HMR memory isn't here yet.

**Comment by MarkPieszak** [comment]
I didn't get that issue, you're on windows 10?

**Comment by hheexx** [comment]
Ok, we need HMR. I am using ngtools only for production and keeping old loader stack for dev.
Also I am keeping JIT under node. I don't know if there is any benefit of running AOT except maybe faster startup ?

Yea, I hit that bug under win10.
I had to add:
`	aotPlugin._compilerHost._resolve = function (path_to_resolve) {
		path_1 = require("path");
		path_to_resolve = aotPlugin._compilerHost._normalizePath(path_to_resolve);
		if (path_to_resolve[0] == '.') {
			return aotPlugin._compilerHost._normalizePath(path_1.join(aotPlugin._compilerHost.getCurrentDirectory(), path_to_resolve));
		}
		else if (path_to_resolve[0] == '/' || path_to_resolve.match(/^\w:\//)) {
			return path_to_resolve;
		}
		else {
			return aotPlugin._compilerHost._normalizePath(path_1.join(aotPlugin._compilerHost._basePath, path_to_resolve));
		}
	};
`

**Comment by MarkPieszak** [comment]
The express engine I'm using building needs to be updated to only do AoT actually, doing JIT during SSR is just slower and there's no benefits to it. Still plenty to work on, never enough time! 😓

There's still HMR, it just doesn't hold the app state currently.

**Pull request merged**
