### PR TITLE
I18n support - Can switch between English and Norwegian

### LINKED ISSUE #111: Support for i18n
It would be great to include internationalization support by default :)

### PR DESCRIPTION
**Pull request by hakonamatata**
Added i18n support

Translated part of the side to Norwegian to show an example of it working. 

One problem: 

```
export function createTranslateLoader(http: Http) {

    // BUG: URLs requested via Http on the server must be absolute
    // TODO: Should not hardcode localhost, should use APP_BASE_HREF!!
    return new TranslateHttpLoader(http, 'http://localhost:5000/assets/i18n/', '.json');
}

```

^ I hardcoded the url of the translation files to localhost at port 5000, this should be changed to the current APP_BASE_HREF. 

But it work fine to run locally at port 5000. 

Closes #111

### CODE REVIEW

**Comment by MarkPieszak** [comment]
ngx-translate very nice! 👍 
Does it work fine when it's using `APP_BASE_HREF` ?

**Comment by hakonamatata** [comment]
I assume it will work using `APP_BASE_HREF`, but could not figure out exactly how to inject that into the `createTranslateLoader` function :confused:

**Comment by MarkPieszak** [comment]
Merged & fixed it! @hakonamatata 
Oh by the way the SignalR demo was acting up? Just commented out the link in the navigation, but not sure what went wrong?

```typescript
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [Http, [new Inject(), APP_BASE_HREF]] // <--
            }
        }),

export function createTranslateLoader(http: Http, APP_BASE_HREF) {
    // i18n files are in `wwwroot/assets/`
    return new TranslateHttpLoader(http, `${APP_BASE_HREF}/assets/i18n/`, '.json');
}
```

**Comment by hakonamatata** [comment]
Glad I can help :blush:

I'll take a second look at the signalR implementation too

**Comment by hakonamatata** [comment]
Tried your solution, but I get an error here: 

deps: [Http, **[new Inject(),** APP_BASE_HREF]]


```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2346	Supplied parameters do not match any signature of call target.	aspnetcore-angular2-universal (tsconfig project)	C:\front-end\aspnetcore-angular2-universal\Client\app\app.module.ts	50	Active

```

**Comment by MarkPieszak** [comment]
Yeah looking at it now too, not sure where that came from, worked a second ago

**Comment by MarkPieszak** [comment]
Fixed now via: https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/61d7c0b61a4915e9b6c5c2b39a2fdfc1ac26712e

They changed the way you pass `new Inject()` now in deps, found it in the changelog. Fml 👾

**Pull request merged**
