### PR TITLE
Swagger changes

### PR DESCRIPTION
**Pull request by LiverpoolOwen**
I have just realised how to limit the pull requests to the specific commits. Funnily enough via https://stackoverflow.com/questions/5256021/send-a-pull-request-on-github-for-only-latest-commit
which you edited ha. :)

### CODE REVIEW

**Comment by MarkPieszak** [comment]
Haha small world right 😅
Want me to merge it in, did you ever figure out the SpaRoute issue?

**Comment by LiverpoolOwen** [comment]
Indeed it is! 

Yeah I figured it out. It currently uses the SPA fall back route when there is not controller but I added a condition so that it will it will only fall back if it's not swagger. It feels a bit hacky though. What do you think? Change is in the start-up file.

**Comment by MarkPieszak** [comment]
I saw that, seems good to me though! Can always change it later if we find a different way of doing it.
This is great stuff though man, thanks for the help 👍👍

**Comment by LiverpoolOwen** [comment]
No worries mate. This is an awesome template you have made. I will hopefully be making use of it a lot in future.

**Comment by LiverpoolOwen** [comment]
I seem to have introduced a bug, it can't find the asset file now when in dev mode. Maybe we should back this out?

**Comment by LiverpoolOwen** [comment]
I have fixed the bug so will send another pull request

**Comment by MarkPieszak** [comment]
Excellent ! 🍾
Yeah hoping to just keep making it better and easier to use as time goes on. I need to upgrade / fix the webpack stuff next

**Pull request merged**
