### PR TITLE
Updated Main method adhering to best practices regarding Main method and DB initialization code

### PR DESCRIPTION
**Pull request by schnerring**
First of all great repo, I used it as a starting point instead of the very similar Angular 2 template integrated in VS2017 and very much enjoy it.

I'm still in the process of understanding AspNetCore but if I understand correctly your initialization code was still missing a _very crucial_ step of refactoring when you migrated from AspNetCore 1.x to 2.0. You don't include EF migrations out of the box but people trying to integrate it into your starting package as is will inherently run into some trouble while trying.

I included the links that provide the necessary information in the commit message, regardless here are the most important bits:

- [Update Main method in Program.cs](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#update-main-method-in-programcs)
> The adoption of this new 2.0 pattern is highly recommended and is required for product features like Entity Framework (EF) Core Migrations to work. 

I left the comment `//context.Database.Migrate();` in there to suggest where EF migrations should now go. Let me know if it would be interesting to support migrations out of the box, I could contribute some code for that.
- [Move database initialization code](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#move-database-initialization-code)
> As of 2.0, it's bad practice to do anything in `BuildWebHost` except build and configure the web host. Anything that is about running the application should be handled outside of `BuildWebHost` — typically in the `Main` method of Program.cs.
- I also updated the logging configuration (added appsettings.Development.json). This consists of more verbose logging configuration. The appsettings.json now is less verbose and suited for environments outside of "Development"

If you have any questions or suggestions let me know.

### CODE REVIEW

**Comment by ebeeb** [comment]
I messed up, I just realized I missed removing the initialization code from the `Configure` method. The `DbInitializer.Initialize(context);` and the injected `SpaDbContext context´ of course has to go.

**Comment by ebeeb** [comment]
Not sure why you closed this, your DB initialization code is still [in the wrong place](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/3269cf0ef6bd4b6aad3357cbdb472b1ca07dc4f0/Startup.cs#L94).

Gonna quote Microsoft's official standpoint again from [Move database initialization code](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#move-database-initialization-code) describing how to migrate from 1.x to 2

> As of 2.0, it's bad practice to do anything in BuildWebHost except build and configure the web host. Anything that's about running the application should be handled outside of BuildWebHost — typically in the Main method of Program.cs.

Just saying, IMHO this is how it was done prior to AspNetCore 2.0

**Comment by MarkPieszak** [comment]
Hey @ebeeb 
It looks like since there were so many changes around this time, it created a crazy amount of conflicts, it might be easier to just create a new PR with the few changes for the DB work? Let me know, and sorry about that ! :(

**Comment by ebeeb** [comment]
No worries, thanks for letting me know. When I have some time on my hands im gonna create a new PR.

**Pull request closed without merging**
